package org.jboss.mjolnir.server.report;

import org.jboss.mjolnir.client.domain.Report;
import org.jboss.mjolnir.server.bean.ApplicationParameters;
import org.jboss.mjolnir.server.bean.MailingBean;

import javax.ejb.EJB;
import java.util.UUID;

/**
 * @author Tomas Hofman (thofman@redhat.com)
 */
public abstract class AbstractReportBean<D> {

    private static final String REPORTING_EMAIL_KEY = "application.reporting_email";

    @EJB
    private ApplicationParameters applicationParameters;

    @EJB
    private MailingBean mailingBean;

    private String reportName;

    protected AbstractReportBean(String reportName) {
        this.reportName = reportName;
    }

    public Report<D> generateReport() {
        final D data = loadData();
        final String content = createReportContent(data);
        return new Report<D>(createUuid(), data, content);
    }

    public void emailReport() {
        final String reportingEmail = applicationParameters.getMandatoryParameter(REPORTING_EMAIL_KEY);
        final String subject = "Mjolnir Report: " + reportName;
        final Report report = generateReport();
        final String body = "Following report on GitHub subscriptions was generated by Mjolnir.\n\n" + report.getContent();

        mailingBean.sendEmail(reportingEmail, reportingEmail, subject, body);
    }

    public String getReportName() {
        return reportName;
    }

    private String createUuid() {
        return UUID.randomUUID().toString();
    }

    protected abstract D loadData();

    protected abstract String createReportContent(D data);

}
